// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test
void test();
RcppExport SEXP _zrtrading_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test();
    return R_NilValue;
END_RCPP
}
// simulate_student
std::vector<int> simulate_student();
RcppExport SEXP _zrtrading_simulate_student() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(simulate_student());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_zrtrading_test", (DL_FUNC) &_zrtrading_test, 0},
    {"_zrtrading_simulate_student", (DL_FUNC) &_zrtrading_simulate_student, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_zrtrading(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
