# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
test <- function() {
    invisible(.Call('_zrtrading_test', PACKAGE = 'zrtrading'))
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
simulate_student <- function() {
    .Call('_zrtrading_simulate_student', PACKAGE = 'zrtrading')
}

