# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    invisible(.Call('_zrtrading_test', PACKAGE = 'zrtrading'))
}

simulate_student <- function() {
    .Call('_zrtrading_simulate_student', PACKAGE = 'zrtrading')
}

